version: '3.8'
services:
  monster-container: # das ist der name des containers
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      PORTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      # das ist ein freier name des netzwerkes
      - monster-ag
networks:
  monster-ag:
